### ISSUE TITLE
Crash inside verve lib

### ISSUE THREAD

**Issue by rslama** [VerveWireless/verve-android-adsdk#12] opened 2018-03-20 12:40 UTC
Our users are complain about crash apps and log uncover this:

Fatal Exception: java.lang.NumberFormatException: For input string: "+HY1wdyDdrTTF6m7Zvp5NQ=="
       at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
       at java.lang.Float.parseFloat(Float.java:459)
       at com.vervewireless.advert.d.k.a(SourceFile:89)
       at com.vervewireless.advert.d.au.e(SourceFile:66)
       at com.vervewireless.advert.b.e.a(SourceFile:254)
       at com.vervewireless.advert.b.e.e(SourceFile:272)
       at com.vervewireless.advert.b.e.c(SourceFile:320)
       at com.vervewireless.advert.b.b.b(SourceFile:178)
       at com.vervewireless.advert.b.b$a.onConnected(SourceFile:198)
       at com.google.android.gms.common.internal.zzae.zzk(Unknown Source)
       at com.google.android.gms.common.api.internal.zzba.zzj(Unknown Source)
       at com.google.android.gms.common.api.internal.zzao.zzaie(Unknown Source)
       at com.google.android.gms.common.api.internal.zzao.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbi.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzt.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzn.zzakr(Unknown Source)
       at com.google.android.gms.common.internal.zze.zzw(Unknown Source)
       at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source)
       at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Used verve lib v. 3.7.0

**Comment by christinamatthews** [comment] 2018-03-21 14:23
Thanks @rslama for the feedback. We have been unable to reproduce the issue so far, however are putting preventive measures in place to prevent this issue for our next release. We will keep you updated on the progress.

**Comment by christinamatthews** [comment] 2018-04-03 21:07
@rslama - This fix will be in our next release. Thank you!

**Comment by christinamatthews** [comment] 2018-05-10 19:43
Issue resolved in v3.7.2.

**Closed** 2018-05-10 19:43 UTC
